### AUTH

### Registrar usuário
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "nome": "Nathan Gonçalves",
  "email": "nathan@email.com",
  "senha": "senha123",
  "tipo": "cliente"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "nathan@email.com",
  "senha": "senha123"
}

### Perfil autenticado (precisa de token Bearer)
GET http://localhost:3000/auth/profile
Authorization: Bearer SEU_TOKEN_AQUI


### USER

### Listar usuários
GET http://localhost:3000/user

### Ver usuário específico
GET http://localhost:3000/user/1

### Criar usuário
POST http://localhost:3000/user
Content-Type: application/json

{
  "nome": "Nathan Gonçalves",
  "email": "nathan@email.com",
  "senha": "senha123",
  "tipo": "cliente"
}

### Atualizar usuário
PUT http://localhost:3000/user/1
Content-Type: application/json

{
  "nome": "Nathan Gonçalves Atualizado",
  "email": "nathan@email.com"
}

### Remover usuário
DELETE http://localhost:3000/user/1


### RESTAURANT

### Listar restaurantes
GET http://localhost:3000/restaurant

### Ver restaurante
GET http://localhost:3000/restaurant/1

### Criar restaurante
POST http://localhost:3000/restaurant
Content-Type: application/json

{
   "nome": "Pizzaria do Nathann",
  "descricao": "A melhor pizza da cidade",
  "endereco": "Rua das Pizzas, 200",
  "telefone": "(61) 1525-1289",
  "tipo": "casual"
}

### Atualizar restaurante
PUT http://localhost:3000/restaurant/1
Content-Type: application/json

{
  "nome": "Pizzaria do Nathann",
  "descricao": "Nova descricao",
  "endereco": "Rua das Pizzas, 200",
  "telefone": "(61) 1525-1289",
  "tipo": "casual"
}

### Remover restaurante
DELETE http://localhost:3000/restaurant/1


### CATEGORY

### Listar categorias
GET http://localhost:3000/category

### Ver categoria
GET http://localhost:3000/category/1

### Criar categoria
POST http://localhost:3000/category
Content-Type: application/json

{
  "nome": "Pizza"
}

### Atualizar categoria
PUT http://localhost:3000/category/1
Content-Type: application/json

{
  "nome": "Pizza Atualizada"
}

### Remover categoria
DELETE http://localhost:3000/category/1


### PRODUCT

### Listar produtos
GET http://localhost:3000/product

### Ver produto
GET http://localhost:3000/product/1

### Criar produto
POST http://localhost:3000/product
Content-Type: application/json

{
   "id": 1,
  "nome": "Hambúrguer",
  "preco": 25.50,
  "restaurantId": seu id gerado,
  "categoryId": 3
}

### Atualizar produto
PUT http://localhost:3000/product/1
Content-Type: application/json

{
   "id": 1,
  "nome": "Pizza Calabresa",
  "preco": 25.50,
  "restaurantId": 5,
  "categoryId": 5
}

### Remover produto
DELETE http://localhost:3000/product/1


### ORDER

### Listar pedidos
GET http://localhost:3000/order

### Ver pedido
GET http://localhost:3000/order/1

### Criar pedido
POST http://localhost:3000/order
Content-Type: application/json

{
  "userId": 1,
  "addressId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 2
    }
  ],
  "paymentId": 1
}

### Atualizar pedido
PUT http://localhost:3000/order/1
Content-Type: application/json

{
  "userId": 1,
  "addressId": 1,
  "items": [
    {
      "productId": 1,
      "quantity": 3
    }
  ],
  "paymentId": 1
}

### Remover pedido
DELETE http://localhost:3000/order/1


### ORDER-ITEM

### Listar itens do pedido
GET http://localhost:3000/order-item

### Ver item do pedido
GET http://localhost:3000/order-item/1

### Criar item de pedido
POST http://localhost:3000/order-item
Content-Type: application/json

{
  "orderId": 2,
  "productId": 1,
  "quantidade": 2
}

### Atualizar item de pedido
PUT http://localhost:3000/order-item/1
Content-Type: application/json

{
  "orderId": 2,
  "productId": 1,
  "quantidade": 3
}

### Remover item de pedido
DELETE http://localhost:3000/order-item/1


### ADDRESS

### Listar endereços
GET http://localhost:3000/address

### Ver endereço
GET http://localhost:3000/address/1

### Criar endereço
POST http://localhost:3000/address
Content-Type: application/json

{
  "street": "Rua das Pizzas",
  "number": "100",
  "neighborhood": "Centro",
  "city": "Campinas",
  "state": "SP",
  "zipCode": "13000-000",
  "userId": 1
}

### Atualizar endereço
PUT http://localhost:3000/address/1
Content-Type: application/json

{
  "street": "Rua dos Burgers",
  "number": "200",
  "neighborhood": "Centro",
  "city": "Campinas",
  "state": "SP",
  "zipCode": "13000-000",
  "userId": 1
}

### Remover endereço
DELETE http://localhost:3000/address/1


### PAYMENT

### Listar formas de pagamento
GET http://localhost:3000/payment

### Ver pagamento
GET http://localhost:3000/payment/1

### Criar pagamento
POST http://localhost:3000/payment
Content-Type: application/json

{
  "method": "credit_card",
  "status": "approved",
  "amount": 79.98,
  "userId": 1
}

### Atualizar pagamento
PUT http://localhost:3000/payment/1
Content-Type: application/json

{
  "method": "pix",
  "status": "pending",
  "amount": 99.99,
  "userId": 1
}

### Remover pagamento
DELETE http://localhost:3000/payment/1


### FAVORITE RESTAURANT

### Listar favoritos
GET http://localhost:3000/favorite-restaurant

### Ver favorito
GET http://localhost:3000/favorite-restaurant/1

### Adicionar restaurante favorito
POST http://localhost:3000/favorite-restaurant
Content-Type: application/json

{
  "userId": 1,
  "restaurantId": 1
}

### Atualizar favorito
PUT http://localhost:3000/favorite-restaurant/1
Content-Type: application/json

{
  "userId": 1,
  "restaurantId": 2
}

### Remover favorito
DELETE http://localhost:3000/favorite-restaurant/1


### REVIEW

### Listar avaliações
GET http://localhost:3000/review

### Ver avaliação
GET http://localhost:3000/review/1

### Criar avaliação
POST http://localhost:3000/review
Content-Type: application/json

{
  "userId": 1,
  "restaurantId": 1,
  "rating": 5,
  "comentario": "Excelente comida e atendimento!"
}

### Atualizar avaliação
PUT http://localhost:3000/review/1
Content-Type: application/json

{
  "userId": 1,
  "restaurantId": 1,
  "rating": 4,
  "comentario": "Gostei muito, mas demorou um pouco."
}

### Remover avaliação
DELETE http://localhost:3000/review/1
