### Criar UF
POST http://localhost:3000/uf
Content-Type: application/json

{
  "nome": "São Paulo",
  "sigla": "SP"
}

### Criar Cidade (uf id: 1)
POST http://localhost:3000/cidade
Content-Type: application/json

{
  "nome": "Campinas",
  "uf": {
    "id": 1
  }
}

### Criar Estudante (cidade id: 1)
POST http://localhost:3000/estudante
Content-Type: application/json

{
  "nome": "Maria Oliveira",
  "matricula": "20240001",
  "email": "maria.oliveira@example.com",
  "dt_nascimento": "2002-05-12",
  "cidade": {
    "id": 1
  }
}

### Listar UFs
GET http://localhost:3000/uf

### Listar Cidades
GET http://localhost:3000/cidade

### Listar Estudantes
GET http://localhost:3000/estudante

### Ver um estudante
GET http://localhost:3000/estudante/2

### Atualizar UF
PATCH http://localhost:3000/uf/1
Content-Type: application/json

{
  "nome": "São Paulo Atualizado"
}

### Deletar Estudante
DELETE http://localhost:3000/estudante/1
# --- NOVOS ENDPOINTS ---
### GET /
GET http://localhost:3000/


### GET /order
GET http://localhost:3000/order


### GET /order/:id
GET http://localhost:3000/order/1


### POST /order
POST http://localhost:3000/order
Content-Type: application/json

{
  
}


### PUT /order/:id
PUT http://localhost:3000/order/1
Content-Type: application/json

{
  
}


### DELETE /order/:id
DELETE http://localhost:3000/order/1


### GET /restaurant
GET http://localhost:3000/restaurant


### GET /restaurant/:id
GET http://localhost:3000/restaurant/1


### POST /restaurant
POST http://localhost:3000/restaurant
Content-Type: application/json

{
  
}


### PUT /restaurant/:id
PUT http://localhost:3000/restaurant/1
Content-Type: application/json

{
  
}


### DELETE /restaurant/:id
DELETE http://localhost:3000/restaurant/1


### GET /category
GET http://localhost:3000/category


### GET /category/:id
GET http://localhost:3000/category/1


### POST /category
POST http://localhost:3000/category
Content-Type: application/json

{
  
}


### PUT /category/:id
PUT http://localhost:3000/category/1
Content-Type: application/json

{
  
}


### DELETE /category/:id
DELETE http://localhost:3000/category/1


### GET /auth/profile
GET http://localhost:3000/auth/profile


### POST /auth/register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  
}


### POST /auth/login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  
}


### GET /payment
GET http://localhost:3000/payment


### GET /payment/:id
GET http://localhost:3000/payment/1


### POST /payment
POST http://localhost:3000/payment
Content-Type: application/json

{
  
}


### PUT /payment/:id
PUT http://localhost:3000/payment/1
Content-Type: application/json

{
  
}


### DELETE /payment/:id
DELETE http://localhost:3000/payment/1


### GET /user
GET http://localhost:3000/user


### GET /user/:id
GET http://localhost:3000/user/1


### POST /user
POST http://localhost:3000/user
Content-Type: application/json

{
  
}


### PUT /user/:id
PUT http://localhost:3000/user/1
Content-Type: application/json

{
  
}


### DELETE /user/:id
DELETE http://localhost:3000/user/1


### GET /favorite-restaurant
GET http://localhost:3000/favorite-restaurant


### GET /favorite-restaurant/:id
GET http://localhost:3000/favorite-restaurant/1


### POST /favorite-restaurant
POST http://localhost:3000/favorite-restaurant
Content-Type: application/json

{
  
}


### PUT /favorite-restaurant/:id
PUT http://localhost:3000/favorite-restaurant/1
Content-Type: application/json

{
  
}


### DELETE /favorite-restaurant/:id
DELETE http://localhost:3000/favorite-restaurant/1


### GET /product
GET http://localhost:3000/product


### GET /product/:id
GET http://localhost:3000/product/1


### POST /product
POST http://localhost:3000/product
Content-Type: application/json

{
  
}


### PUT /product/:id
PUT http://localhost:3000/product/1
Content-Type: application/json

{
  
}


### DELETE /product/:id
DELETE http://localhost:3000/product/1


### GET /review
GET http://localhost:3000/review


### GET /review/:id
GET http://localhost:3000/review/1


### POST /review
POST http://localhost:3000/review
Content-Type: application/json

{
  
}


### PUT /review/:id
PUT http://localhost:3000/review/1
Content-Type: application/json

{
  
}


### DELETE /review/:id
DELETE http://localhost:3000/review/1


### GET /address
GET http://localhost:3000/address


### GET /address/:id
GET http://localhost:3000/address/1


### POST /address
POST http://localhost:3000/address
Content-Type: application/json

{
  
}


### PUT /address/:id
PUT http://localhost:3000/address/1
Content-Type: application/json

{
  
}


### DELETE /address/:id
DELETE http://localhost:3000/address/1


### GET /order-item
GET http://localhost:3000/order-item


### GET /order-item/:id
GET http://localhost:3000/order-item/1


### POST /order-item
POST http://localhost:3000/order-item
Content-Type: application/json

{
  
}


### PUT /order-item/:id
PUT http://localhost:3000/order-item/1
Content-Type: application/json

{
  
}


### DELETE /order-item/:id
DELETE http://localhost:3000/order-item/1


### GET /teste
GET http://localhost:3000/teste


### GET /teste/:id
GET http://localhost:3000/teste/1


### POST /teste
POST http://localhost:3000/teste
Content-Type: application/json

{
  
}


### PATCH /teste/:id
PATCH http://localhost:3000/teste/1
Content-Type: application/json

{
  
}


### DELETE /teste/:id
DELETE http://localhost:3000/teste/1

